/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,jsx}",
    "./src/components/**/*.{js,jsx}",
    "./src/widgets/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#2563EB",
          hover: "#1D4ED8",
          light: "#EFF6FF",
        },
        secondary: "#0D9488",
        page: "#F9FAFB",
        cream: "#F7F4EF",
        terracotta: {
          DEFAULT: "#C75B3F",
          hover: "#B5492F",
          light: "#FFF5F2",
        },
        card: "#FFFFFF",
        "text-primary": "#111827",
        "text-secondary": "#4B5563",
        "text-tertiary": "#9CA3AF",
        border: "#E5E7EB",
        "footer-bg": "#111827",
        "footer-text": "#D1D5DB",
        badge: {
          "remote-bg": "#ECFDF5",
          "remote-text": "#059669",
          "hybrid-bg": "#FEF3C7",
          "hybrid-text": "#D97706",
          "onsite-bg": "#EFF6FF",
          "onsite-text": "#2563EB",
          "internship-bg": "#F3E8FF",
          "internship-text": "#7C3AED",
          "fulltime-bg": "#F0FDF4",
          "fulltime-text": "#15803D",
        },
        whatsapp: "#25D366",
        v3: {
          ink: "var(--v3-ink)",
          "ink-2": "var(--v3-ink-2)",
          "ink-3": "var(--v3-ink-3)",
          paper: "var(--v3-paper)",
          "paper-2": "var(--v3-paper-2)",
          "paper-3": "var(--v3-paper-3)",
          line: "var(--v3-line)",
          "line-soft": "var(--v3-line-soft)",
          mute: "var(--v3-mute)",
          "mute-2": "var(--v3-mute-2)",
          accent: "var(--v3-accent)",
          "accent-2": "var(--v3-accent-2)",
          "accent-soft": "var(--v3-accent-soft)",
          "accent-deep": "var(--v3-accent-deep)",
          acid: "var(--v3-acid)",
          rose: "var(--v3-rose)",
          green: "var(--v3-green-pulse)",
          warn: "var(--v3-warn-orange)",
        },
        linkedin: {
          bg: "#F4EEE4",
          surface: "#FCF8F1",
          accent: "#C75B3F",
          "accent-hover": "#B5492F",
          "accent-light": "#FFF5F2",
          charcoal: "#2C2C2C",
          ink: "#1A1614",
          "ink-soft": "#3D332E",
          border: "#E5E0D8",
          rule: "#D9CFBF",
          muted: "#8A8580",
          highlight: "#C99B3C",
          "proof-bg": "#1A1614",
          "proof-surface": "#2A2320",
          "proof-rule": "#3D332E",
        },
      },
      fontFamily: {
        sans: ["Inter", "Noto Sans", "system-ui", "-apple-system", "sans-serif"],
        "serif-display": ["var(--font-instrument-serif)", "Georgia", "serif"],
        dm: ["var(--font-dm-sans)", "Inter", "sans-serif"],
        "sans-linkedin": ["var(--font-bricolage)", "system-ui", "sans-serif"],
        "mono-proof": ["var(--font-jetbrains-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
        "v3-serif": ["var(--font-instrument-serif)", "Times New Roman", "serif"],
        "v3-sans": ["var(--font-geist)", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        "v3-mono": ["var(--font-geist-mono)", "ui-monospace", "monospace"],
      },
      fontSize: {
        hero: ["3rem", { lineHeight: "1.1", letterSpacing: "-0.025em", fontWeight: "700" }],
        "page-title": ["2.25rem", { lineHeight: "1.2", fontWeight: "700" }],
        "section-header": ["1.875rem", { lineHeight: "1.3", fontWeight: "600" }],
        "card-title": ["1.25rem", { lineHeight: "1.4", fontWeight: "600" }],
        body: ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        small: ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        caption: ["0.75rem", { lineHeight: "1.5", fontWeight: "500", letterSpacing: "0.05em" }],
      },
      spacing: {
        18: "4.5rem",
        22: "5.5rem",
      },
      maxWidth: {
        content: "1200px",
        card: "800px",
      },
      borderRadius: {
        card: "12px",
        button: "8px",
        input: "8px",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)",
        "card-hover": "0 10px 25px rgba(0,0,0,0.08), 0 4px 10px rgba(0,0,0,0.04)",
        nav: "0 1px 3px rgba(0,0,0,0.1)",
        "search-focus": "0 0 0 3px rgba(37,99,235,0.1)",
        "linkedin-card": "0 2px 8px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        "linkedin-card-hover": "0 8px 24px rgba(0,0,0,0.08), 0 2px 8px rgba(0,0,0,0.04)",
        letterpress:
          "0 1px 0 rgba(26,22,20,0.04), 0 8px 20px -12px rgba(26,22,20,0.12)",
        "letterpress-hover":
          "0 1px 0 rgba(26,22,20,0.06), 0 14px 28px -14px rgba(26,22,20,0.22)",
        "letterpress-inset":
          "inset 0 -1px 0 rgba(26,22,20,0.15), 0 1px 0 rgba(255,255,255,0.6)",
        "proof-panel":
          "0 30px 60px -30px rgba(26,22,20,0.45), 0 12px 24px -18px rgba(26,22,20,0.25)",
        "v3-card-hover": "0 8px 24px rgba(10,14,26,0.06)",
        "v3-dropdown": "0 10px 30px rgba(10,14,26,0.10)",
      },
      backgroundImage: {
        "v3-dot-grid":
          "radial-gradient(circle at 1px 1px, rgba(10,14,26,0.08) 1px, transparent 0)",
        "v3-whatsapp": "linear-gradient(135deg, #128C7E 0%, #25D366 100%)",
        "v3-rail-fade": "linear-gradient(180deg, var(--v3-paper) 0%, var(--v3-paper-2) 100%)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "ink-in": {
          "0%": { backgroundColor: "rgba(201,155,60,0.38)" },
          "70%": { backgroundColor: "rgba(201,155,60,0.18)" },
          "100%": { backgroundColor: "transparent" },
        },
        "press-reveal": {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "stamp-bloom": {
          "0%": { transform: "scale(0.8)", opacity: "0" },
          "60%": { transform: "scale(1.04)", opacity: "1" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "v3-pulse-ring": {
          "0%, 100%": { boxShadow: "0 0 0 4px rgba(0,184,107,0.18)" },
          "50%":      { boxShadow: "0 0 0 8px rgba(0,184,107,0.06)" },
        },
        "v3-sheet-up": {
          "0%": { transform: "translateY(100%)" },
          "100%": { transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.3s ease-out forwards",
        shimmer: "shimmer 1.5s ease-in-out infinite",
        marquee: "marquee 30s linear infinite",
        "ink-in": "ink-in 520ms ease-out",
        "press-reveal": "press-reveal 360ms ease-out forwards",
        "stamp-bloom": "stamp-bloom 220ms ease-out",
        "v3-pulse-ring": "v3-pulse-ring 2s ease-in-out infinite",
        "v3-sheet-up": "v3-sheet-up 240ms cubic-bezier(0.2,0.8,0.2,1) forwards",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
