export const CATEGORIES = [
  { id: "resume", label: "Resume & CV", emoji: "\ud83d\udcdd" },
  { id: "interview", label: "Interview Prep", emoji: "\ud83c\udf99\ufe0f" },
  { id: "salary", label: "Salary & Compensation", emoji: "\ud83d\udcb0" },
  { id: "dsa", label: "DSA & Coding Practice", emoji: "\ud83d\udcbb" },
  { id: "aptitude", label: "Aptitude & Reasoning", emoji: "\ud83e\udde0" },
  { id: "learning", label: "Learning & Upskilling", emoji: "\ud83d\udcda" },
];

export const SORT_OPTIONS = [
  { value: "featured", label: "Featured" },
  { value: "az", label: "A\u2013Z" },
  { value: "newest", label: "Newest" },
];

export const TOOLS = [
  // Resume & CV
  {
    id: "teal-resume",
    name: "Teal Resume Builder",
    shortDescription: "AI-powered resume builder that tailors your resume to each job posting automatically.",
    category: "resume",
    pricing: "freemium",
    pricingNote: "Free plan available",
    url: "https://www.tealhq.com/resume-builder",
    isFeatured: true,
    isNew: false,
    rating: 4.7,
    ratingSource: "G2",
    platforms: ["Web", "Chrome Extension"],
    lastVerified: "Mar 2026",
  },
  {
    id: "zety",
    name: "Zety",
    shortDescription: "Professional resume templates with step-by-step guidance and expert tips.",
    category: "resume",
    pricing: "freemium",
    pricingNote: "Free basic, paid from \u20b9399/mo",
    url: "https://zety.com",
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    ratingSource: "Trustpilot",
    platforms: ["Web"],
    lastVerified: "Mar 2026",
  },
  {
    id: "overleaf",
    name: "Overleaf (LaTeX)",
    shortDescription: "Collaborative LaTeX editor perfect for clean, ATS-friendly academic resumes.",
    category: "resume",
    pricing: "free",
    pricingNote: "Free for personal use",
    url: "https://www.overleaf.com",
    isFeatured: false,
    isNew: false,
    rating: 4.6,
    ratingSource: "G2",
    platforms: ["Web"],
    lastVerified: "Feb 2026",
  },

  // Interview Prep
  {
    id: "pramp",
    name: "Pramp",
    shortDescription: "Free peer-to-peer mock interviews with real engineers — practice live coding & behavioral.",
    category: "interview",
    pricing: "free",
    url: "https://www.pramp.com",
    isFeatured: true,
    isNew: false,
    rating: 4.5,
    ratingSource: "G2",
    platforms: ["Web"],
    lastVerified: "Mar 2026",
  },
  {
    id: "interviewbit",
    name: "InterviewBit",
    shortDescription: "Structured interview prep with curated problems, video solutions, and mock interviews.",
    category: "interview",
    pricing: "free",
    url: "https://www.interviewbit.com",
    isFeatured: false,
    isNew: false,
    rating: 4.4,
    ratingSource: "G2",
    platforms: ["Web", "Android"],
    lastVerified: "Feb 2026",
  },
  {
    id: "big-interview",
    name: "Big Interview",
    shortDescription: "AI-powered interview training with recorded practice sessions and expert feedback.",
    category: "interview",
    pricing: "paid",
    pricingNote: "From \u20b9499/mo",
    url: "https://www.biginterview.com",
    isFeatured: false,
    isNew: true,
    rating: 4.3,
    ratingSource: "Trustpilot",
    platforms: ["Web"],
    lastVerified: "Mar 2026",
  },

  // Salary & Compensation
  {
    id: "levels-fyi",
    name: "Levels.fyi",
    shortDescription: "Verified salary data from top tech companies — compare offers, levels, and total comp.",
    category: "salary",
    pricing: "free",
    url: "https://www.levels.fyi",
    isFeatured: true,
    isNew: false,
    rating: 4.8,
    ratingSource: "G2",
    platforms: ["Web"],
    lastVerified: "Mar 2026",
  },
  {
    id: "glassdoor-salary",
    name: "Glassdoor Salary",
    shortDescription: "Salary estimates, company reviews, and interview experiences from real employees.",
    category: "salary",
    pricing: "free",
    url: "https://www.glassdoor.co.in/Salaries",
    isFeatured: false,
    isNew: false,
    rating: 4.3,
    ratingSource: "Trustpilot",
    platforms: ["Web", "Android", "iOS"],
    lastVerified: "Feb 2026",
  },
  {
    id: "ambitionbox",
    name: "AmbitionBox",
    shortDescription: "India-focused salary data, company reviews, and interview questions for tech roles.",
    category: "salary",
    pricing: "free",
    url: "https://www.ambitionbox.com",
    isFeatured: false,
    isNew: false,
    rating: 4.2,
    ratingSource: "G2",
    platforms: ["Web", "Android"],
    lastVerified: "Mar 2026",
  },

  // DSA & Coding Practice
  {
    id: "leetcode",
    name: "LeetCode",
    shortDescription: "The go-to platform for DSA prep with 3000+ problems, contests, and company-wise questions.",
    category: "dsa",
    pricing: "freemium",
    pricingNote: "Premium from \u20b9599/mo",
    url: "https://leetcode.com",
    isFeatured: true,
    isNew: false,
    rating: 4.7,
    ratingSource: "G2",
    platforms: ["Web", "Android", "iOS"],
    lastVerified: "Mar 2026",
  },
  {
    id: "geeksforgeeks",
    name: "GeeksforGeeks Practice",
    shortDescription: "India's largest DSA practice platform with topic-wise problems and editorial solutions.",
    category: "dsa",
    pricing: "free",
    url: "https://practice.geeksforgeeks.org",
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    ratingSource: "G2",
    platforms: ["Web", "Android", "iOS"],
    lastVerified: "Mar 2026",
  },
  {
    id: "code360",
    name: "Code360 (Coding Ninjas)",
    shortDescription: "Guided coding paths with mentorship, mock tests, and placement preparation resources.",
    category: "dsa",
    pricing: "freemium",
    pricingNote: "Free problems, paid courses",
    url: "https://www.naukri.com/code360",
    isFeatured: false,
    isNew: false,
    rating: 4.4,
    ratingSource: "G2",
    platforms: ["Web", "Android"],
    lastVerified: "Feb 2026",
  },

  // Aptitude & Reasoning
  {
    id: "prepinsta",
    name: "PrepInsta",
    shortDescription: "Company-specific aptitude prep with previous year questions and shortcuts for freshers.",
    category: "aptitude",
    pricing: "free",
    url: "https://prepinsta.com",
    isFeatured: false,
    isNew: false,
    rating: 4.3,
    ratingSource: "G2",
    platforms: ["Web"],
    lastVerified: "Mar 2026",
  },
  {
    id: "indiabix",
    name: "IndiaBIX",
    shortDescription: "Comprehensive aptitude, reasoning, and verbal ability practice with detailed explanations.",
    category: "aptitude",
    pricing: "free",
    url: "https://www.indiabix.com",
    isFeatured: false,
    isNew: false,
    rating: 4.1,
    ratingSource: "Trustpilot",
    platforms: ["Web"],
    lastVerified: "Feb 2026",
  },
  {
    id: "freshersworld-aptitude",
    name: "Freshersworld Aptitude",
    shortDescription: "Free aptitude tests designed for campus placements and fresher recruitment drives.",
    category: "aptitude",
    pricing: "free",
    url: "https://www.freshersworld.com/aptitude-questions",
    isFeatured: false,
    isNew: true,
    rating: 4.0,
    ratingSource: "Trustpilot",
    platforms: ["Web"],
    lastVerified: "Mar 2026",
  },

  // Learning & Upskilling
  {
    id: "freecodecamp",
    name: "freeCodeCamp",
    shortDescription: "Completely free, project-based web dev curriculum — HTML, CSS, JS, React, Node, and more.",
    category: "learning",
    pricing: "free",
    url: "https://www.freecodecamp.org",
    isFeatured: false,
    isNew: false,
    rating: 4.8,
    ratingSource: "G2",
    platforms: ["Web"],
    lastVerified: "Mar 2026",
  },
  {
    id: "cs50",
    name: "CS50 (Harvard)",
    shortDescription: "Harvard's legendary intro to CS — covers C, Python, SQL, web, and AI. 100% free on edX.",
    category: "learning",
    pricing: "free",
    pricingNote: "Free audit, paid certificate",
    url: "https://cs50.harvard.edu/x",
    isFeatured: false,
    isNew: false,
    rating: 4.9,
    ratingSource: "G2",
    platforms: ["Web"],
    lastVerified: "Mar 2026",
  },
  {
    id: "odin-project",
    name: "The Odin Project",
    shortDescription: "Open-source full-stack curriculum — learn by building real projects with community support.",
    category: "learning",
    pricing: "free",
    url: "https://www.theodinproject.com",
    isFeatured: false,
    isNew: false,
    rating: 4.7,
    ratingSource: "G2",
    platforms: ["Web"],
    lastVerified: "Feb 2026",
  },
];
